version: '3.3'

services:
  db:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
       - 5432:5432
  
  dashboard:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.local
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
    ports: 
      - 5005:80