const ACTIONS = {
  ADD_MESSAGE : 'ADD_MESSAGE',
  DELETE_MESSAGE: 'DELETE_MESSAGE',
  ADD_MESSAGES: 'ADD_MESSAGES',
  ADD_CONTACT: 'ADD_CONTACT',
  DELETE_CONTACT: 'DELETE_CONTACT',
  ADD_CONTACTS: 'ADD_CONTACTS',
  SET_ACTIVE_USER: 'SET_ACTIVE_USER',
  SET_ACTIVE_CONVERSATION: 'SET_ACTIVE_CONVERSATION',
  SEARCH_REQUEST: 'SEARCH_REQUEST',
  ADD_ALL_CONTACTS: 'ADD_ALL_CONTACTS',
  LOGIN: 'LOGIN'
};

Object.freeze(ACTIONS);

export default ACTIONS;